#!/usr/bin/env python3
"""Generate the Mathlib-only single-file distribution from the modular library."""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "standalone" / "Operator_Phase_Retrieval_Standalone.lean"
IMPORT = re.compile(r"^import (\S+)\s*$", re.MULTILINE)


def render() -> str:
    visited: set[str] = set()
    visiting: set[str] = set()
    modules: list[tuple[str, str]] = []
    external: dict[str, None] = {}

    def visit(module: str) -> None:
        if module in visited:
            return
        if module in visiting:
            raise ValueError(f"Cyclic import: {module}")
        path = ROOT / (module.replace(".", "/") + ".lean")
        if not path.is_file():
            raise FileNotFoundError(path)
        visiting.add(module)
        source = path.read_text(encoding="utf-8")
        for dependency in IMPORT.findall(source):
            if dependency == "OperatorPhaseRetrieval" or dependency.startswith("OperatorPhaseRetrieval."):
                visit(dependency)
            elif dependency.startswith("Mathlib."):
                external[dependency] = None
            else:
                raise ValueError(f"Unexpected external import: {dependency}")
        visiting.remove(module)
        visited.add(module)
        body = IMPORT.sub("", source).strip()
        if module not in {"OperatorPhaseRetrieval", "OperatorPhaseRetrieval.MathlibImports"}:
            modules.append((module, body))

    visit("OperatorPhaseRetrieval")
    library_files = {"OperatorPhaseRetrieval." + p.stem for p in (ROOT / "OperatorPhaseRetrieval").glob("*.lean")}
    missing = library_files - visited
    if missing:
        raise ValueError(f"Library modules missing from the root import: {sorted(missing)}")
    header = "\n".join("import " + name for name in external)
    header += "\n\n/-!\n# Phase retrieval with three unitary operators\n\n"
    header += "Generated by scripts/make_standalone.py. Edit the modular source files.\n"
    header += "Lean 4.33.0; Mathlib v4.33.0. Only Mathlib is imported.\n"
    header += "The main theorem is `OperatorPhaseRetrieval.main : MainStatement`.\n"
    header += "Do not import this file together with the modular library.\n-/\n"
    chunks = [f"\n\n/- Source: {name.replace('.', '/')}.lean -/\n\n{body}\n" for name, body in modules]
    return header + "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed file differs from generated output.")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("Standalone file is out of date; run python3 scripts/make_standalone.py", file=sys.stderr)
            return 1
        print("Standalone file is up to date.")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
